{"name": "Запрос PUT \"Принять заказ\" для заказа с некорректным курьером", "status": "passed", "steps": [{"name": "Отправка запроса PUT: Принятие заказа с id \"333537\", id курьера \"8534665\", ожидается сообщение: \"Курьера с таким id не существует\" с кодом \"404\"", "status": "passed", "start": 1723400711639, "stop": 1723400711737}], "parameters": [{"name": "courier_id", "value": "8534665"}, {"name": "error_code", "value": "404"}, {"name": "error_message", "value": "'Курьера с таким id не существует'"}], "start": 1723400711638, "stop": 1723400711738, "uuid": "bafa2a09-c5ba-4933-ac32-8d33c20aca46", "historyId": "b02850d3d79654ea4a98c4995fc050b0", "testCaseId": "dc6a47e840e00f54eb0762757eabdae9", "fullName": "test.test_take_order.TestTakeOrder#test_take_order_invalid_courier_id_error_invalid_data", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_take_order"}, {"name": "subSuite", "value": "TestTakeOrder"}, {"name": "host", "value": "MacBook-Air-Elizaveta.local"}, {"name": "thread", "value": "16582-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_take_order"}]}