{"name": "Запрос PUT \"Принять заказ\" для заказа с некорректным id заказа", "status": "failed", "statusDetails": {"message": "AssertionError: assert (404 == 400)\n +  where 404 = <Response [404]>.status_code", "trace": "self = <test_take_order.TestTakeOrder object at 0x1040eee70>, order_id = '', error_code = 400, error_message = 'Недостаточно данных для поиска'\nsign_up_new_courier = <Response [201]>, log_in_courier = <Response [200]>, delete_courier = None\n\n    @allure.title('Запрос PUT \"Принять заказ\" для заказа с некорректным id заказа')\n    @pytest.mark.parametrize('order_id, error_code, error_message', [['', 400, variables.order_empty_data],\n                                                                     [random.randrange(1111111, 9999999),\n                                                                      404, variables.order_not_found]])\n    def test_take_order_invalid_order_id_error_invalid_data(self, order_id, error_code, error_message,\n                                                            sign_up_new_courier, log_in_courier, delete_courier):\n        courier_id = log_in_courier.json()['id']\n        with allure.step(f'Отправка запроса PUT: Принятие заказа с id \"{order_id}\", id курьера \"{courier_id}\", '\n                         f'ожидается сообщение: \"{error_message}\" с кодом \"{error_code}\"'):\n            response_take_order = requests.put(f'{variables.TAKE_ORDER}/{order_id}?courierId={courier_id}')\n            get_error_message = response_take_order.json()['message']\n>       assert response_take_order.status_code == error_code and get_error_message == error_message\nE       assert (404 == 400)\nE        +  where 404 = <Response [404]>.status_code\n\ntest/test_take_order.py:44: AssertionError"}, "steps": [{"name": "Отправка запроса PUT: Принятие заказа с id \"\", id курьера \"367030\", ожидается сообщение: \"Недостаточно данных для поиска\" с кодом \"400\"", "status": "passed", "start": 1723400711925, "stop": 1723400711989}], "parameters": [{"name": "order_id", "value": "''"}, {"name": "error_code", "value": "400"}, {"name": "error_message", "value": "'Недостаточно данных для поиска'"}], "start": 1723400711924, "stop": 1723400711990, "uuid": "17d1934b-1642-4079-ad13-9306b8df5383", "historyId": "2e1b30373e8b2fe357d406ea13d66b1e", "testCaseId": "45ad7cfa7a3427bc4cb266b1ad3db1ba", "fullName": "test.test_take_order.TestTakeOrder#test_take_order_invalid_order_id_error_invalid_data", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_take_order"}, {"name": "subSuite", "value": "TestTakeOrder"}, {"name": "host", "value": "MacBook-Air-Elizaveta.local"}, {"name": "thread", "value": "16582-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_take_order"}]}