{"name": "Запрос GET \"Получить заказ по его номеру\" для заказа с некорректным трек-номером", "status": "passed", "steps": [{"name": "Отправка запроса GET: Получение заказа по номеру \"7680828\", ожидается ошибка \"Заказ не найден\" с кодом \"404\"", "status": "passed", "start": 1723400679855, "stop": 1723400679955}], "parameters": [{"name": "order_num", "value": "7680828"}, {"name": "error_code", "value": "404"}, {"name": "error_message", "value": "'Заказ не найден'"}], "start": 1723400679854, "stop": 1723400679956, "uuid": "d18eeedf-bde7-445f-8827-1d1c06279aff", "historyId": "a3f12886329de19950480ac5e0d222f6", "testCaseId": "70bc97e7459a93f96cdfe1e9a1254917", "fullName": "test.test_create_order.TestGetOrder#test_get_order_via_track_num_invalid_data_error_invalid_data", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "MacBook-Air-Elizaveta.local"}, {"name": "thread", "value": "16582-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_create_order"}]}